'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  id: {
    'brand.name': 'Ardana Perkasa Group',
    'brand.short': 'APG',
    'brand.logoAlt': 'Logo APG',

    // Navigation
    'nav.home': 'Beranda',
    'nav.about': 'Profil Perusahaan',
    'nav.structure': 'Struktur Organisasi',
    'nav.subsidiaries': 'Anak Perusahaan',
    'nav.announcements': 'Pengumuman',
    'nav.news': 'Berita',
    'announcements.news.desc': 'Informasi terbaru, pembaruan korporasi, dan aktivitas APG yang relevan untuk publik.',
    'nav.contact': 'Hubungi Kami',
    'nav.menu.open': 'Buka menu utama',
    'nav.menu.close': 'Tutup menu utama',
    'nav.menu.label': 'Menu',
    'nav.services': 'Layanan',
    'nav.information': 'Informasi',
    'nav.career': 'Karir',
    'nav.annual_report': 'Laporan Tahunan',
    'nav.achievements': 'Prestasi',
    'nav.testimonials': 'Testimoni',
    'nav.gallery': 'Galeri APG',
    'nav.vision_mission': 'Visi & Misi',
    'nav.language': 'Bahasa',
    'nav.aria': 'Navigasi utama',
    'nav.about_history': 'Tentang Perusahaan',
    'nav.about_history.desc': 'Ringkasan perjalanan APG dan fondasi holding yang membangun ekosistem lintas sektor.',
    'nav.vision_mission.desc': 'Arah strategis dan komitmen jangka panjang APG untuk pertumbuhan berkelanjutan.',
    'nav.gallery.desc': 'Kegiatan korporasi dan momen strategis APG dalam format visual.',
    'nav.structure_chart': 'Bagan Struktur Organisasi',
    'nav.management': 'Manajemen',
    'nav.subsidiaries_all': 'Lihat Semua Anak Perusahaan',
    'org.chart.header': 'BADAN STRUKTUR ORGANISASI PT ARDANA PERKASA GROUP',
    'org.chart.gm': 'RAPAT UMUM PEMEGANG',
    'org.chart.gm.2': 'SAHAM',
    'org.chart.board': 'DEWAN KOMISARIS',
    'org.chart.ceo.1': 'DIREKTUR',
    'org.chart.ceo.2': 'UTAMA',
    'org.chart.opsdir.1': 'DIREKTUR',
    'org.chart.opsdir.2': 'OPERASIONAL',
    'org.chart.head.finance': 'KADIV KEUANGAN',
    'org.chart.head.it': 'KADIV IT',
    'org.chart.head.support': 'KADIV SUPPORT',
    'org.chart.head.ops': 'KADIV OPERASIONAL',
    'org.chart.spv.acc': 'SPV ACCOUNTING, TAX &\nREPORTING',
    'org.chart.staff.acc': 'STAFF ACCOUNTING',
    'org.chart.staff.tax': 'STAFF TAX',
    'org.chart.spv.finance': 'SPV FINANCE &\nCORPORATE PLANNING',
    'org.chart.staff.finance': 'STAFF FINANCE',
    'org.chart.staff.bizplan.1': 'STAFF BISNIS',
    'org.chart.staff.bizplan.2': 'PLAN',
    'org.chart.spv.itprog': 'SPV IT PROGRAMMER',
    'org.chart.staff.itprog.1': 'STAFF IT\nPROGRAMMER 1',
    'org.chart.staff.itprog.2': 'STAFF IT\nPROGRAMMER 2',
    'org.chart.staff.itprog.3': 'STAFF IT\nPROGRAMMER 3',
    'org.chart.staff.itprog.4': 'STAFF IT\nPROGRAMMER 4',
    'org.chart.staff.itprog.5': 'STAFF IT\nPROGRAMMER 5',
    'org.chart.staff.itprog.6': 'STAFF IT\nPROGRAMMER 6',
    'org.chart.spv.itsupport': 'SPV IT SUPPORT',
    'org.chart.staff.itsupport.1': 'STAFF IT\nSUPPORT 1',
    'org.chart.staff.itsupport.2': 'STAFF IT\nSUPPORT 2',
    'org.chart.staff.itsupport.3': 'STAFF IT\nSUPPORT 3',
    'org.chart.spv.marketing': 'SPV MARKETING',
    'org.chart.staff.digital': 'STAFF DIGITAL\nMARKETING',
    'org.chart.staff.markexec.1': 'STAFF MARKETING',
    'org.chart.staff.markexec.2': 'EXECUTIVE',
    'org.chart.spv.compliance': 'SPV COMPLIANCE',
    'org.chart.staff.audit.1': 'STAFF AUDIT',
    'org.chart.staff.audit.2': 'INTERNAL',
    'org.chart.staff.legal.1': 'STAFF LEGAL &',
    'org.chart.staff.legal.2': 'KEPATUHAN',
    'org.chart.spv.hr': 'SPV SDM & UMUM',
    'org.chart.staff.hr': 'STAFF SDM',
    'org.chart.staff.general': 'STAFF UMUM',
    'org.chart.spv.cosec.1': 'SPV SEKRETARIS',
    'org.chart.spv.cosec.2': 'PERUSAHAAN',
    'org.chart.staff.relations.1': 'STAFF HUBUNGAN',
    'org.chart.staff.relations.2': 'KELEMBAGAAN',
    'org.chart.staff.corpcom.1': 'KOMUNIKASI',
    'org.chart.staff.corpcom.2': 'KORPORASI',
    'org.chart.exec.driver.1': 'PELAKSA',
    'org.chart.exec.driver.2': 'DRIVER 1',
    'org.chart.exec.driver2.1': 'PELAKSANA',
    'org.chart.exec.driver2.2': 'DRIVER 2',
    'org.chart.exec.ob.1': 'PELAKSANA',
    'org.chart.exec.ob.2': 'OB',
    'org.chart.exec.courier.1': 'PELAKSANA',
    'org.chart.exec.courier.2': 'KURIR',
    'language.id.aria': 'Bahasa Indonesia',
    'language.en.aria': 'English',

    // Hero
    'hero.headline': 'Membangun Ekosistem Lintas Sektor dengan Standar Enterprise',
    'hero.subheadline': 'APG adalah holding company yang mengembangkan ekosistem bisnis lintas sektor dengan tata kelola enterprise.',
    'hero.illustrationAlt': 'Ilustrasi hero APG',
    'hero.cta.discover': 'Jelajahi Anak Perusahaan',
    'hero.cta.ecosystem': 'Pelajari Ekosistem',
    'hero.about.badge': 'ARDANA PERKASA GROUP',
    'hero.about.p1':
      'APG merupakan perusahaan holding yang menaungi beberapa anak perusahaan yang bergerak di sektor pendukung Lembaga Keuangan di antaranya PT. Buana Perkasa Rajanegara (BPR Bonding), PT. Dwi Kusuma Perkasa (DWP Insurance), PT. Perkasa Lintas Nasional Consultant (PLN Consultant), dan PT. Pataka Prima Perkasa Consultant (Pataka Consultant).',
    'hero.about.p2':
      'APG juga menaungi anak perusahaan yang bergerak di sektor olahraga, memperluas jangkauannya dalam mendukung berbagai industri yang berkontribusi pada perkembangan ekonomi dan sosial.',
    'hero.vision.title': 'Visi',
    'hero.vision.desc': 'Menjadi mitra terpercaya dan terdepan dalam mendukung ekosistem lembaga keuangan dan pengembangan industri olahraga.',
    'hero.mission.title': 'Misi',
    'hero.mission.desc': 'Menyediakan solusi komprehensif, andal, dan inovatif yang mendorong pertumbuhan ekonomi serta sosial.',
    'hero.cta.learnMore': 'Pelajari lebih lanjut tentang perusahaan kami',
    'hero.mock.tag': 'Workspace',
    'hero.mock.accounts.label': 'Akun',
    'hero.mock.accounts.value': 'Pertumbuhan stabil',
    'hero.mock.reports.label': 'Laporan',
    'hero.mock.reports.value': 'Data aman',
    'hero.mock.years.label': 'Pengalaman',
    'hero.mock.years.value': 'Kepemimpinan industri',

    // Intro
    'intro.badge': 'Mendukung Ekosistem Lembaga Keuangan & Olahraga',
    'intro.title.part1': 'Menggerakkan Pertumbuhan',
    'intro.title.highlight': 'Lintas Industri',
    'intro.title.part2': 'dengan Inovasi Strategis & Kemitraan Kuat.',
    'intro.desc': 'Ardana Perkasa Group (APG) adalah perusahaan holding yang menaungi anak perusahaan di sektor pendukung Lembaga Keuangan dan Olahraga.',
    'intro.cta.primary': 'Jelajahi Bisnis Kami',
    'intro.cta.secondary': 'Lihat Laporan Tahunan',
    'intro.card.1.title': 'Jangkauan Luas',
    'intro.card.1.desc': 'Menghubungkan banyak mitra dan jaringan bisnis lintas sektor.',
    'intro.card.2.title': 'Keamanan Terpercaya',
    'intro.card.2.desc': 'Standar enterprise untuk data dan proses yang andal.',
    'intro.card.3.title': 'Pertumbuhan Berkelanjutan',
    'intro.card.3.desc': 'Ekspansi ekosistem yang konsisten dari tahun ke tahun.',
    'intro.card.4.title': 'Infrastruktur',
    'intro.card.4.desc': 'Membangun fondasi operasional untuk eksekusi modern.',

    'trust.inline': 'Dipercaya oleh 200+ mitra lintas industri',

    'hero.card.partners.label': 'Mitra',
    'hero.card.partners.value': '200+',
    'hero.card.industries.label': 'Industri',
    'hero.card.industries.value': '10',

    // Overview
    'overview.tag': 'Ringkasan Perusahaan',
    'overview.title': 'Memimpin Eksekusi Lintas Sektor dengan Tata Kelola Enterprise',
    'overview.desc': 'Kami membangun ekosistem holding yang terstruktur—menghubungkan modal, kapabilitas, dan kemitraan untuk menciptakan pertumbuhan berkelanjutan.',
    'overview.value.1.title': 'Strategic Vision',
    'overview.value.1.desc': 'Holding company multi-sektor dengan fokus pada tata kelola, sinergi, dan nilai jangka panjang.',
    'overview.value.2.title': 'Governance Excellence',
    'overview.value.2.desc': 'Mengembangkan portofolio di finance, insurance, consulting, sports, dan solutions dengan eksekusi disiplin.',
    'overview.value.3.title': 'Sustainable Expansion',
    'overview.value.3.desc': 'Menjadi mitra strategis tepercaya yang mendorong pertumbuhan lintas industri melalui inovasi dan kepatuhan.',
    'overview.value.4.title': 'Ecosystem Partnership',
    'overview.value.4.desc': 'Membangun kolaborasi jangka panjang yang memperkuat ekosistem bisnis dan ketahanan portofolio.',
    'overview.highlight.1.value': '2+',
    'overview.highlight.1.label': 'Tahun Pengalaman',
    'overview.highlight.2.value': '8',
    'overview.highlight.2.label': 'Anak Perusahaan',
    'overview.highlight.3.value': '200+',
    'overview.highlight.3.label': 'Mitra',
    'overview.highlight.4.value': '10',
    'overview.highlight.4.label': 'Industri',
    'overview.cta.primary': 'Jelajahi Bisnis Kami',
    'overview.cta.secondary': 'Lihat Profil Perusahaan',

    // Career
    'career.nav': 'Karir',
    'career.hero.tag': 'Karir di APG',
    'career.hero.title': 'Bangun Karir Anda di Berbagai Industri',
    'career.hero.subtitle': 'Bergabunglah dengan Ardana Perkasa Group dan tumbuh dalam ekosistem lintas sektor yang dinamis.',
    'career.hero.cta.open': 'Lihat Lowongan',
    'career.hero.cta.companies': 'Lihat Perusahaan',
    'career.empty': 'Tidak ada lowongan ditemukan.',
    'career.modal.responsibilities': 'Tanggung Jawab',
    'career.modal.requirements': 'Kualifikasi',
    'career.modal.close': 'Tutup',
    'career.intro.headline': 'Bangun Karier Bersama Ardana Perkasa Group',
    'career.intro.subtext': 'Kami selalu mencari talenta terbaik untuk berkembang bersama ekosistem bisnis kami.',
    'career.why_join.title': 'Mengapa Berkarier di APG?',
    'career.why_join.1.title': 'Profesional & Berkembang',
    'career.why_join.1.desc': 'Lingkungan kerja dinamis yang mendukung pertumbuhan kompetensi Anda.',
    'career.why_join.2.title': 'Lintas Industri',
    'career.why_join.2.desc': 'Kesempatan eksplorasi karier di berbagai sektor bisnis holding.',
    'career.why_join.3.title': 'Stabilitas Holding',
    'career.why_join.3.desc': 'Keamanan berkarier dalam ekosistem bisnis yang kokoh dan berkelanjutan.',
    'career.why_join.4.title': 'Inovasi & Kolaborasi',
    'career.why_join.4.desc': 'Budaya kerja modern yang menghargai ide kreatif dan kerjasama tim.',
    'struktur.sectors.title': 'Jelajahi Peluang di Berbagai Sektor',
    'struktur.komisaris': 'Dewan Komisaris',
    'struktur.direktur_utama': 'Direktur Utama',
    'struktur.direktur': 'Direktur',
    'struktur.manager_keuangan': 'Manager Keuangan',
    'struktur.manager_operasional': 'Manager Operasional',
    'struktur.supervisor_keuangan': 'Supervisor Keuangan',
    'struktur.kadiv_keuangan': 'Kepala Divisi Keuangan',
    'struktur.kadiv_operasional': 'Kepala Divisi Operasional',
    'struktur.kadiv_keuangan_operasional': 'Kadiv Keuangan + Operasional',
    'struktur.supervisor_it': 'Supervisor IT',
    'struktur.staff_keuangan': 'Staff Keuangan',
    'struktur.staff_operasional': 'Staff Operasional',
    'struktur.management': 'Manajemen',
    'career.search.guidance.title': 'Mulai Pencarian Karier Anda',
    'career.search.guidance.desc': 'Cari posisi, bidang, atau nama perusahaan untuk menemukan peluang yang sesuai.',
    'career.search.suggested': 'Pencarian Populer:',
    'career.search.results_for': 'Hasil pencarian untuk:',
    'career.keywords.it': 'IT',
    'career.keywords.finance': 'Keuangan',
    'career.keywords.marketing': 'Marketing',
    'career.keywords.hr': 'SDM',
    'career.keywords.operasional': 'Operasional',
    'career.jobs_found_single': 'lowongan ditemukan',
    'career.jobs_found_plural': 'lowongan ditemukan',
    'career.job.type.full_time': 'Penuh Waktu',
    'career.job.type.contract': 'Kontrak',
    'career.job.type.internship': 'Magang',
    'career.job.cta.detail': 'Detail Pekerjaan',
    'career.job.cta.apply': 'Lamar Sekarang',
    'career.search.placeholder': 'Cari posisi atau perusahaan...',
    'career.search.button': 'Cari',
    'career.reset_filter': 'Atur Ulang',

    // Metrics
    'metrics.subsidiaries': 'Anak Perusahaan',
    'metrics.partners': 'Mitra',
    'metrics.sectors': 'Sektor',
    'metrics.tag': 'STATISTIK',
    'metrics.title': 'Skala yang Terukur. Eksekusi yang Terbukti.',
    'metrics.desc': 'Indikator utama yang mencerminkan pertumbuhan, jangkauan, dan kekuatan ekosistem bisnis APG.',
    'metrics.caption': 'Indikator skala enterprise',

    // About Preview
    'about.preview.tag': 'Tentang Kami',
    'about.preview.title': 'Sekilas Ardana Perkasa Group',
    'about.preview.desc': 'Ardana Perkasa Group (APG) hadir sebagai entitas holding strategis yang berfokus pada pengembangan ekosistem bisnis berkelanjutan.',
    'about.preview.cta': 'Pelajari Tentang Kami',
    'about.preview.imageAlt': 'Ardana Perkasa Group - Enterprise Holding',

    // Business Focus
    'focus.tag': 'EKOSISTEM BISNIS',
    'focus.title.part1': 'Sinergi Lintas Sektor untuk',
    'focus.title.part2': 'Masa Depan',
    'focus.1.title': 'Tata Kelola',
    'focus.1.desc': 'Kerangka GCG untuk keputusan yang transparan dan terukur.',
    'focus.2.title': 'Kepatuhan',
    'focus.2.desc': 'Proses yang selaras regulasi untuk meminimalkan risiko dan menjaga kepercayaan.',
    'focus.3.title': 'Inovasi',
    'focus.3.desc': 'Solusi modern untuk mempercepat pertumbuhan dan meningkatkan daya saing.',
    'focus.4.title': 'Kemitraan',
    'focus.4.desc': 'Kolaborasi jangka panjang yang memperluas dampak lintas industri.',
    'focus.5.title': 'Eksekusi',
    'focus.5.desc': 'Implementasi disiplin dengan standar enterprise di seluruh portofolio.',

    // Ecosystem
    'ecosystem.tag': 'Ekosistem Bisnis',
    'ecosystem.title.part1': 'Portofolio Terintegrasi untuk ',
    'ecosystem.title.part2': 'Pertumbuhan Berkelanjutan',
    'ecosystem.finance': 'Keuangan',
    'ecosystem.insurance': 'Asuransi',
    'ecosystem.consulting': 'Konsultasi',
    'ecosystem.sports': 'Olahraga',
    'ecosystem.solutions': 'Solusi',
    'ecosystem.finance.tag': 'Layanan finansial terpadu.',
    'ecosystem.insurance.tag': 'Proteksi aset & risiko.',
    'ecosystem.consulting.tag': 'Strategi bisnis adaptif.',
    'ecosystem.sports.tag': 'Ekosistem olahraga dinamis.',
    'ecosystem.solutions.tag': 'Solusi operasional cerdas.',

    // Subsidiaries
    'subsidiaries.tag': 'JARINGAN INSTITUSIONAL',
    'subsidiaries.title': 'Ekosistem Perusahaan Unggulan',
    'subsidiaries.desc': 'Membangun sinergi lintas sektor melalui anak perusahaan pilihan yang menjadi pemimpin di bidangnya.',
    'subsidiaries.cta': 'Jelajahi Semua Anak Perusahaan',
    'subsidiaries.card.cta': 'Lihat Detail',
    'subsidiaries.card.label': 'Anak Perusahaan',

    // Why Choose Us
    'why.tag': 'Pilar Nilai Strategis',
    'why.title': 'Kerangka Kerja Institusional Kami',
    'why.desc': 'Kami beroperasi dengan standar tata kelola enterprise, memastikan setiap inisiatif strategis memberikan nilai berkelanjutan dan memperkuat resiliensi ekosistem holding.',
    'why.1.title': 'Visi Strategis',
    'why.1.desc': 'Fokus jangka panjang pada sinergi lintas sektor, mengarahkan portofolio menuju keunggulan pasar.',
    'why.2.title': 'Keunggulan Tata Kelola',
    'why.2.desc': 'Standar kepatuhan tertinggi dan manajemen risiko untuk menjaga kepercayaan pemangku kepentingan.',
    'why.3.title': 'Pertumbuhan Berkelanjutan',
    'why.3.desc': 'Ekspansi terukur yang berpusat pada penciptaan nilai, ketahanan ekonomi, dan tanggung jawab lingkungan.',
    'why.4.title': 'Kemitraan Ekosistem',
    'why.4.desc': 'Aliansi strategis yang memperkuat rantai pasok dan memperluas kapasitas eksekusi nasional.',

    // Leadership
    'leadership.tag': 'KEPEMIMPINAN',
    'leadership.title': 'Dipimpin oleh Profesional Berpengalaman',
    'leadership.desc': 'Jajaran manajemen berfokus pada tata kelola, strategi, dan eksekusi yang berorientasi hasil.',
    'leadership.1.role': 'Komisaris Utama',
    'leadership.2.role': 'Komisaris',
    'leadership.3.role': 'Direktur Utama',
    'leadership.4.role': 'Direktur',
    'leadership.5.role': 'Direktur Keuangan',

    // News/Insights
    'news.1.tag': 'Strategi',
    'news.1.title': 'APG Holding Memulai Ekspansi Strategis di Teknologi Olahraga',
    'news.1.excerpt': 'Menjelajahi sinergi baru antara layanan keuangan dan infrastruktur olahraga untuk mendorong pertumbuhan ekosistem di tahun 2025.',
    'news.2.tag': 'Tata Kelola',
    'news.2.title': 'Laporan Tata Kelola Kuartalan: Memperkuat Transparansi Perusahaan',
    'news.2.excerpt': 'Tinjauan komprehensif tentang kerangka kerja GCG kami yang diperbarui dan dampaknya terhadap keunggulan operasional anak perusahaan.',
    'news.3.tag': 'Inovasi',
    'news.3.title': 'Integrasi Ekosistem Digital: Menstandarisasi Infrastruktur Lintas Sektor',
    'news.3.excerpt': 'Mengimplementasikan platform digital terpadu untuk meningkatkan kolaborasi dan keamanan data di seluruh unit APG.',
    'news.3.date': '15 April 2025',

    // Gallery
    'gallery.item.1.title': 'Pertemuan Strategis Pimpinan',
    'gallery.item.1.category': 'Korporasi',
    'gallery.item.2.title': 'Sinergi Operasional Kantor',
    'gallery.item.2.category': 'Operasional',
    'gallery.item.3.title': 'Inovasi Ekosistem Digital',
    'gallery.item.3.category': 'Teknologi',
    'gallery.item.4.title': 'Fasilitas Pengembangan Atlet',
    'gallery.item.4.category': 'Olahraga',
    'gallery.item.5.title': 'Audit Tata Kelola Perusahaan',
    'gallery.item.5.category': 'Governance',
    'gallery.item.6.title': 'Penghargaan Ekosistem Tahunan',
    'gallery.item.6.category': 'Achievement',
    'gallery.tag.enterprise_activities': 'Aktivitas Enterprise',

    // Insights
    'insights.tag': 'WAWASAN',
    'insights.title': 'Berita & Wawasan',
    'insights.desc': 'Perspektif, pembaruan, dan cerita ekosistem untuk menjaga website tetap hidup dan relevan.',
    'insights.cta': 'Lihat Semua',
    'insights.readMore': 'Baca Selengkapnya',
    'insights.tag.corporate_insights': 'Wawasan Korporasi',
    'insights.1.tag': 'Corporate',
    'insights.1.title': 'Meningkatkan Daya Saing melalui Sinergi Portofolio',
    'insights.1.excerpt': 'Bagaimana strategi holding menyelaraskan kapabilitas lintas sektor untuk menciptakan pertumbuhan yang berkelanjutan.',
    'insights.1.date': '12 Mei 2025',
    'insights.2.tag': 'Governance',
    'insights.2.title': 'Tata Kelola sebagai Keunggulan Kompetitif',
    'insights.2.excerpt': 'Mengapa standar enterprise dan kepatuhan memperkuat kepercayaan mitra dan pemangku kepentingan.',
    'insights.2.date': '28 April 2025',
    'insights.3.tag': 'Ecosystem',
    'insights.3.title': 'Membangun Ekosistem Bisnis yang Modern & Adaptif',
    'insights.3.excerpt': 'Pendekatan APG dalam mengembangkan ekosistem yang tangguh di tengah perubahan pasar.',
    'insights.3.date': '15 April 2025',

    // Ecosystem Extra
    'ecosystem.strategic_ecosystem': 'Ekosistem Strategis',
    'ecosystem.strategic_desc': 'Portofolio terdiversifikasi yang terhubung oleh tata kelola enterprise dan visi strategis bersama.',
    'ecosystem.explore_title': 'Jelajahi Seluruh Ekosistem',
    'ecosystem.explore_desc': 'Temukan bagaimana anak perusahaan kami bersinergi untuk menciptakan dampak nasional.',
    'ecosystem.explore_cta': 'Lihat Portofolio',

    // CTA
    'cta.tag': 'KOLABORASI',
    'cta.title': 'Mari Bangun Masa Depan Bersama',
    'cta.desc': 'Mulai percakapan untuk kolaborasi, kemitraan, atau peluang strategis lintas sektor.',
    'cta.primary': 'Hubungi Kami',
    'cta.secondary': 'Jadi Mitra',

    // Trust
    'trust.partners': 'Dipercaya oleh Mitra Terkemuka',
    'trust.partnerAlt': 'Mitra',
    'trust.cta.title': 'Mari Bangun Sinergi Bersama',
    'trust.cta.button': 'Hubungi Kami',
    'trust.testimonial.1.quote': 'APG adalah mitra strategis yang membawa standar eksekusi enterprise ke level yang baru.',
    'trust.testimonial.1.author': 'Mitra Strategis',
    'trust.testimonial.2.quote': 'Tata kelola yang kuat dan sinergi lintas sektor membuat APG menjadi holding yang visioner.',
    'trust.testimonial.2.author': 'Direktur Anak Perusahaan',

    // Process
    'process.tag': 'PROSES KERJA',
    'process.title': 'Standard Work Process',
    'process.desc': 'Alur kerja terstandarisasi untuk memastikan kualitas eksekusi, transparansi, dan hasil yang terukur.',
    'process.step1.title': 'Discovery',
    'process.step1.desc': 'Pemetaan kebutuhan, konteks bisnis, dan tujuan strategis.',
    'process.step2.title': 'Planning',
    'process.step2.desc': 'Penyusunan rencana, timeline, dan KPI yang jelas.',
    'process.step3.title': 'Execution',
    'process.step3.desc': 'Implementasi terarah dengan monitoring dan kontrol kualitas.',
    'process.step4.title': 'Reporting',
    'process.step4.desc': 'Pelaporan progres dan evaluasi untuk perbaikan berkelanjutan.',

    // Gallery
    'gallery.tag': 'AKTIVITAS KORPORASI',
    'gallery.title': 'Aktivitas di APG Holding',
    'gallery.cta': 'Lihat Galeri Lengkap',
    'gallery.images.meeting': 'Pertemuan Korporasi',
    'gallery.images.collaboration': 'Kolaborasi Kantor',
    'gallery.images.success': 'Kesuksesan Tim',

    // Illustration
    'illustration.tag': 'ILUSTRASI INTERAKTIF',
    'illustration.title': 'Buat tampilan homepage lebih hidup dengan animasi UI halus.',
    'illustration.desc': 'Elemen kecil di sekitar ilustrasi bergerak lembut untuk memberi kesan modern tanpa mengganggu fokus pengguna.',
    'illustration.badge.ui': 'UI',
    'illustration.badge.done': 'Selesai',
    'illustration.badge.checklist': 'Checklist',

    // Scroll Cinema
    'cinema.brand': 'Ardana Perkasa Group',
    'cinema.title': 'Membangun Masa Depan Melalui Inovasi dan Kolaborasi',
    'cinema.desc': 'Kami menghadirkan solusi terintegrasi untuk mendukung pertumbuhan bisnis yang berkelanjutan.',

    // Not Found
    'notFound.tag': 'TIDAK DITEMUKAN',
    'notFound.desc': 'Halaman yang Anda cari tidak ditemukan.',
    'notFound.cta': 'Kembali ke Beranda',

    // Testimoni
    'testimoni.tag': 'TESTIMONI',
    'testimoni.title': 'Apa Kata Mereka Tentang Kami',
    'testimoni.desc': 'Kami bangga dengan hubungan yang telah kami bangun dengan mitra dan anak perusahaan kami. Berikut adalah beberapa testimoni dari mereka.',
    'testimoni.placeholder.quote': '“Bagian ini akan menampilkan testimoni lengkap dari mitra dan anak perusahaan kami.”',
    'testimoni.placeholder.author': '— Tim Ardana Perkasa Group',

    // Subsidiary Detail
    'subsidiary.detail.tag': 'PROFIL ANAK PERUSAHAAN',
    'subsidiary.detail.back': 'Kembali ke Anak Perusahaan',
    'subsidiary.detail.highlights': 'Sorotan',
    'subsidiary.detail.alignment.title': 'Keselarasan',
    'subsidiary.detail.alignment.desc': 'Seluruh anak perusahaan berada dalam kerangka governance dan portfolio management APG untuk memastikan konsistensi standar, pengelolaan risiko, dan eksekusi berbasis KPI.',
    'subsidiary.detail.alignment.1': 'Model operasi governance-first',
    'subsidiary.detail.alignment.2': 'Transparansi pelaporan dan kontrol',
    'subsidiary.detail.alignment.3': 'Sinergi lintas sektor dan kapabilitas',
    'subsidiary.detail.alignment.4': 'Eksekusi disiplin untuk pertumbuhan',
    'subsidiary.detail.value_creation': 'Penciptaan Nilai',
    'subsidiary.detail.strategic_matrix': 'Matriks Strategis',

    'subsidiary.bpr.sector': 'Agen Asuransi & Penjaminan',
    'subsidiary.bpr.desc': 'Penyedia layanan Bank Garansi dan Surety Bond dengan standar tata kelola yang disiplin.',
    'subsidiary.bpr.highlight.1': 'Kedekatan layanan',
    'subsidiary.bpr.highlight.2': 'Disiplin risiko',
    'subsidiary.bpr.highlight.3': 'Keselarasan portofolio',

    'subsidiary.dwp.sector': 'Agen Asuransi & Penjaminan',
    'subsidiary.dwp.desc': 'Solusi penjaminan dan proteksi risiko untuk mendukung kebutuhan institusi dan portofolio bisnis.',
    'subsidiary.dwp.highlight.1': 'Aktivasi event',
    'subsidiary.dwp.highlight.2': 'Kemitraan brand',
    'subsidiary.dwp.highlight.3': 'Keterlibatan komunitas',

    'subsidiary.sipbro.sector': 'Agen Asuransi & Penjaminan',
    'subsidiary.sipbro.desc': 'Sistem informasi penjaminan yang terintegrasi untuk meningkatkan efisiensi, akurasi, dan monitoring layanan.',
    'subsidiary.sipbro.highlight.1': 'Perangkat operasional',
    'subsidiary.sipbro.highlight.2': 'Enablement layanan',
    'subsidiary.sipbro.highlight.3': 'Disiplin performa',

    'subsidiary.pln.sector': 'Distributor Alat Olahraga',
    'subsidiary.pln.desc': 'Layanan konsultasi dan pendampingan operasional untuk memperkuat eksekusi portofolio dan tata kelola.',
    'subsidiary.pln.highlight.1': 'Enablement lintas fungsi',
    'subsidiary.pln.highlight.2': 'Delivery terstandar',
    'subsidiary.pln.highlight.3': 'Eksekusi enterprise',

    'subsidiary.qjamin.sector': 'Penjaminan Digital',
    'subsidiary.qjamin.desc': 'Assurance dan dukungan governance untuk menjaga kualitas eksekusi portofolio.',
    'subsidiary.qjamin.highlight.1': 'Assurance & kontrol',
    'subsidiary.qjamin.highlight.2': 'Keselarasan governance',
    'subsidiary.qjamin.highlight.3': 'Monitoring kualitas',

    'subsidiary.proteksi.sector': 'Asuransi',
    'subsidiary.proteksi.desc': 'Layanan proteksi yang memperkuat ketahanan finansial dan operasional ekosistem.',
    'subsidiary.proteksi.highlight.1': 'Kerangka proteksi',
    'subsidiary.proteksi.highlight.2': 'Layanan berorientasi pelanggan',
    'subsidiary.proteksi.highlight.3': 'Operasional siap kepatuhan',

    'subsidiary.pataka.sector': 'Olahraga',
    'subsidiary.pataka.desc': 'Inisiatif pengembangan komunitas dan ekosistem olahraga yang berkelanjutan.',
    'subsidiary.pataka.highlight.1': 'Aktivasi komunitas',
    'subsidiary.pataka.highlight.2': 'Model kemitraan',
    'subsidiary.pataka.highlight.3': 'Pertumbuhan brand & ekosistem',

    'subsidiary.prada-bc.sector': 'Klub Olahraga',
    'subsidiary.prada-bc.desc': 'Pembinaan atlet dan pengembangan ekosistem olahraga dengan fasilitas serta standar profesional.',
    'subsidiary.prada-bc.highlight.1': 'Dukungan eksekusi portofolio',
    'subsidiary.prada-bc.highlight.2': 'Delivery berbasis KPI',
    'subsidiary.prada-bc.highlight.3': 'Keselarasan governance enterprise',

    'subsidiary.lps.sector': 'Agen Asuransi & Penjaminan',
    'subsidiary.lps.desc': 'Kapabilitas tata kelola dan standardisasi kontrol untuk konsistensi operasional.',
    'subsidiary.lps.highlight.1': 'Kebijakan & kontrol',
    'subsidiary.lps.highlight.2': 'Disiplin pelaporan',
    'subsidiary.lps.highlight.3': 'Visibilitas risiko',

    'subsidiary.caraka-mulia.sector': 'Pialang dan Konsultan Asuransi',
    'subsidiary.caraka-mulia.desc': 'Solusi proteksi dan manajemen risiko untuk ketahanan ekosistem.',
    'subsidiary.caraka-mulia.highlight.1': 'Kerangka proteksi risiko',
    'subsidiary.caraka-mulia.highlight.2': 'Operasional siap kepatuhan',
    'subsidiary.caraka-mulia.highlight.3': 'Assurance pemangku kepentingan',

    // Tentang Page
    'tentang.hero.badge': 'Siapa Kami',
    'tentang.hero.title': 'Ardana Perkasa Group',
    'tentang.hero.p1': 'Ardana Perkasa Group (APG) adalah salah satu perusahaan holding terkemuka di Indonesia, yang berkomitmen untuk mendorong stabilitas dan pertumbuhan ekonomi melalui solusi bisnis yang inovatif, terpercaya, dan bermanfaat bagi pemegang saham dan pemangku kepentingan.',
    'tentang.hero.p2': 'Selain berfokus pada sektor pendukung lembaga keuangan, APG juga memperluas jangkauan bisnisnya ke sektor olahraga, berkontribusi pada perkembangan industri olahraga di Indonesia, dan menciptakan nilai tambah bagi masyarakat dan perekonomian.',

    'tentang.visi.badge': 'Tentang Kami',
    'tentang.visi.title': 'Visi APG',
    'tentang.visi.desc': 'Menjadi salah satu perusahaan holding terbesar di Indonesia yang mendukung stabilitas dan pertumbuhan ekonomi melalui layanan usaha yang inovatif, terpercaya, dan bermanfaat untuk shareholder maupun stakeholder.',

    'tentang.misi.badge': 'Tentang Kami',
    'tentang.misi.title': 'Misi APG',
    'tentang.misi.1.title': 'Membangun Keunggulan Kompetitif',
    'tentang.misi.1.desc': 'Mengembangkan portofolio yang fokus pada solusi dengan teknologi terkini dan layanan yang unggul untuk memenuhi kebutuhan shareholder maupun stakeholder.',
    'tentang.misi.2.title': 'Mendukung Stabilitas Keuangan',
    'tentang.misi.2.desc': 'Berkontribusi pada ekosistem ekonomi yang stabil dengan menyediakan produk penjaminan yang kredibel, transparan, dan sesuai regulasi.',
    'tentang.misi.3.title': 'Meningkatkan Kepercayaan Pelanggan',
    'tentang.misi.3.desc': 'Menciptakan nilai tambah bagi pelanggan dengan menyediakan layanan yang akurat, cepat, dan berorientasi pada solusi.',
    'tentang.misi.4.title': 'Mendukung Pertumbuhan Bisnis Anak Perusahaan',
    'tentang.misi.4.desc': 'Memberikan dukungan strategis, finansial, dan manajemen kepada anak perusahaan untuk mencapai pertumbuhan yang berkelanjutan.',
    'tentang.misi.5.title': 'Mengutamakan Etika dan Kepatuhan',
    'tentang.misi.5.desc': 'Menjalankan bisnis dengan prinsip-prinsip tata kelola perusahaan yang baik (GCG) serta mematuhi peraturan yang berlaku.',

    'tentang.gallery.badge': 'Tentang Kami',
    'tentang.gallery.title': 'Gallery',

    'tentang.contact.title': 'Untuk Informasi lebih lanjut hubungi kami di :',
    'tentang.contact.address.label': 'Alamat',
    'tentang.contact.address.value': 'Office Tower Fontana, The Mansion Bougenville, Lt. 51 unit BF 51 A1, Jl. Trembesi Blok D Pademangan Timur, Kec. Pademangan, Jakarta Utara',
    'tentang.contact.email.label': 'Email',
    'tentang.contact.email.value': 'info@apg.co.id',
    'tentang.contact.phone.label': 'Telphone',
    'tentang.contact.phone.value': '+6281288885132',

    // Struktur Page
    'struktur.title': 'Struktur Organisasi',
    'struktur.tag': 'Kepemimpinan',
    'struktur.desc': 'Dipimpin oleh jajaran profesional berpengalaman untuk mengorkestrasi sinergi lintas sektor.',
    'struktur.direksi': 'Dewan Direksi',
    'struktur.divisi': 'Kepala Divisi',
    'struktur.cta.title': 'Ingin Bergabung dalam Ekosistem Kami?',
    'struktur.cta.desc': 'Kami selalu terbuka untuk kolaborasi strategis dan talenta profesional.',
    'struktur.cta.view': 'LIHAT PROFIL LENGKAP',

    // Common
    'common.contact_us': 'Hubungi Kami',
    'common.learn_more': 'Pelajari Lebih Lanjut',
    'footer.tagline': 'Enterprise holding company berfokus pada tata kelola, sinergi, dan pertumbuhan portofolio.',
    'footer.cta.title': 'Terhubung dengan Kami',
    'footer.cta.desc': 'Jalin kolaborasi strategis dan akses informasi resmi Ardana Perkasa Group melalui kanal komunikasi kami.',
    'footer.location.label': 'Lokasi',
    'footer.location.value': 'Jakarta Utara',
    'footer.phone.label': 'Telepon',
    'footer.phone.value': '0812 8888 5132',
    'footer.email.label': 'Email',
    'footer.email.value': 'info@apg.co.id',
    'footer.hours.label': 'Jam Operasional',
    'footer.hours.value': 'Senin–Jumat, 08.00 - 17.00 WIB',
    'footer.nav.title': 'Navigasi',
    'footer.social.title': 'Media Sosial',
    'footer.social.linkedin': 'LinkedIn',
    'footer.social.instagram': 'Instagram',
    'footer.social.x': 'X',
    'footer.social.facebook': 'Facebook',
    'footer.social.youtube': 'YouTube',
    'footer.social.tiktok': 'TikTok',
    'footer.legal.privacy': 'Kebijakan Privasi',
    'footer.legal.terms': 'Ketentuan',
    'footer.legal.security': 'Keamanan',
    'footer.copyright': '© {year} {brand}. Hak cipta dilindungi.',

    // Contact Page
    'contact.tag': 'KONTAK',
    'contact.title': 'Hubungi Kami',
    'contact.desc': 'Untuk kolaborasi, kemitraan, atau kebutuhan corporate solutions, tim APG siap terhubung dengan Anda.',
    'contact.map.title': 'Peta lokasi Ardana Perkasa Group - Jakarta Utara',
    'contact.card.address.title': 'Alamat',
    'contact.card.address.value': 'The Mansion Bougenville, Office Tower Fontana, Jakarta Utara',
    'contact.card.email.title': 'Email',
    'contact.card.email.value': 'info@apg.co.id',
    'contact.card.phone.title': 'Telepon',
    'contact.card.phone.value': '0812 8888 5132',
    'contact.card.hours.title': 'Jam Operasional',
    'contact.card.hours.value': 'Senin–Jumat, 08.00 - 17.00 WIB',
    'contact.form.title': 'Kirim Pesan',
    'contact.form.desc': 'Tinggalkan pesan, tim kami akan segera menghubungi Anda kembali.',
    'contact.form.name': 'Nama',
    'contact.form.name.placeholder': 'Nama lengkap',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'Alamat email',
    'contact.form.message': 'Pesan',
    'contact.form.message.placeholder': 'Tuliskan pesan Anda...',
    'contact.form.submit': 'Kirim Pesan',
    'contact.form.success': 'Pesan Anda berhasil terkirim. Tim kami akan segera menghubungi Anda.',
    'contact.form.error': 'Terjadi kesalahan saat mengirim pesan. Silakan coba lagi.',
    'contact.form.direct': 'Inkuiri Langsung',
    'contact.form.sent': 'Terkirim',

    // AI Assistant
    'ai.button': 'Tanya AI',
    'ai.send': 'Kirim',
    'ai.name': 'Ardana Assistant',
    'ai.subtitle': 'Tanya apa saja • Jawaban ramah',
    'ai.aria.close': 'Tutup asisten',
    'ai.aria.open': 'Buka asisten',
    'ai.typing': 'Mengetik…',
    'ai.placeholder': 'Tulis pesan…',
    'ai.error': 'Maaf — aku belum bisa jawab sekarang. Coba lagi ya.',
    'ai.greeting': 'Halo! Aku siap bantu. Mau tanya apa?',
    'ai.suggestion.3': 'Bantu tulis email profesional',

    // Footer Additional
    'footer.col.corporate': 'Korporasi',
    'footer.col.governance': 'Tata Kelola',
    'footer.col.connect': 'Hubungi',
    'footer.gov.directors': 'Dewan Direksi',
    'footer.gov.guidelines': 'Panduan Perusahaan',
    'footer.gov.sustainability': 'Laporan Keberlanjutan',
    'footer.gov.investor': 'Hubungan Investor',
    'footer.gov.conduct': 'Kode Etik',
    'footer.holding_company': 'Holding Company',

    // Tentang Extra
    'tentang.corporate_narrative': 'Narasi Korporasi',
    'tentang.access_gateway': 'Gerbang Akses Korporasi',
    'tentang.info_center': 'Pusat Informasi APG',
    'tentang.info_desc': 'Tim kami siap melayani berbagai kebutuhan strategis, investasi, dan pertanyaan seputar portofolio holding.',
    'tentang.sub.visi_misi.title': 'Visi & Misi',
    'tentang.sub.visi_misi.desc': 'Arah strategis dan komitmen APG untuk mendorong pertumbuhan berkelanjutan melalui tata kelola enterprise.',
    'tentang.sub.gallery.title': 'Galeri APG',
    'tentang.sub.gallery.desc': 'Dokumentasi momen korporat, aktivitas tim, dan ekosistem bisnis APG dalam satu tampilan yang rapi.',

    // Struktur Extra
    'struktur.governance_inquiry': 'Inkuiri Tata Kelola',
    'struktur.finance_head': 'Kepala Keuangan',
    'struktur.ops_head': 'Kepala Operasional',
    'struktur.it_supervisor': 'Supervisor IT',
    'visual.governance': 'Tata Kelola',
    'visual.board_directors': 'Dewan Direksi',
    'visual.ecosystem': 'Ekosistem',
    'visual.high_growth': 'Pertumbuhan Tinggi',
    'visual.companies': 'Perusahaan',
    'visual.sectors': 'Sektor',
    'visual.headquarters': 'Kantor Pusat',
    'visual.jakarta_indonesia': 'Jakarta, Indonesia',

    // Career Jobs Data

    // Career Jobs Data
    'career.job.1.title': 'Software Engineer (Frontend)',
    'career.job.1.desc': 'Kami sedang mencari Software Engineer untuk bergabung dengan tim teknologi kami yang sedang berkembang dan membangun aplikasi web modern untuk ekosistem digital kami.',
    'career.job.1.req.1': '3+ tahun pengalaman dengan React/Next.js',
    'career.job.1.req.2': 'Kemahiran dalam TypeScript dan CSS modern (Tailwind)',
    'career.job.1.req.3': 'Pengalaman dengan manajemen state dan integrasi API',
    'career.job.1.req.4': 'Keterampilan pemecahan masalah yang kuat dan perhatian terhadap detail',
    'career.job.1.resp.1': 'Mengembangkan dan memelihara aplikasi web berkualitas tinggi',
    'career.job.1.resp.2': 'Berkolaborasi dengan desainer dan engineer backend',
    'career.job.1.resp.3': 'Optimasi aplikasi untuk performa dan skalabilitas',
    'career.job.1.resp.4': 'Berpartisipasi dalam tinjauan kode dan diskusi teknis',

    'career.job.2.title': 'Analis Keuangan',
    'career.job.2.desc': 'BPR Bonding sedang mencari Analis Keuangan untuk mendukung proses pelaporan keuangan dan perencanaan strategis kami.',
    'career.job.2.req.1': 'Gelar Sarjana Akuntansi atau Keuangan',
    'career.job.2.req.2': 'Minimal 2 tahun pengalaman dalam analisis keuangan',
    'career.job.2.req.3': 'Kemahiran dalam pemodelan keuangan dan alat pelaporan',
    'career.job.2.req.4': 'Keterampilan analitis dan komunikasi yang sangat baik',
    'career.job.2.resp.1': 'Menyiapkan laporan keuangan bulanan dan triwulanan',
    'career.job.2.resp.2': 'Menganalisis kinerja dan tren keuangan',
    'career.job.2.resp.3': 'Mendukung proses penganggaran dan peramalan',
    'career.job.2.resp.4': 'Membantu audit internal dan eksternal',

    'career.job.3.title': 'Spesialis Asuransi',
    'career.job.3.desc': 'Bergabunglah dengan DWP Insurance sebagai Spesialis Asuransi untuk mengelola klaim klien dan memberikan saran ahli tentang manajemen risiko.',
    'career.job.3.req.1': 'Pengetahuan kuat tentang produk asuransi dan regulasi',
    'career.job.3.req.2': 'Minimal 3 tahun pengalaman di industri asuransi',
    'career.job.3.req.3': 'Kemampuan membangun dan memelihara hubungan dengan klien',
    'career.job.3.req.4': 'Sertifikasi profesional asuransi (AAIK/AIIS) adalah nilai tambah',
    'career.job.3.resp.1': 'Memproses klaim asuransi secara akurat dan efisien',
    'career.job.3.resp.2': 'Melakukan penilaian risiko untuk calon klien',
    'career.job.3.resp.3': 'Menyarankan klien tentang opsi cakupan dan mitigasi risiko',
    'career.job.3.resp.4': 'Memantau tren pasar dan aktivitas kompetitor',

    'career.job.4.title': 'Koordinator Event Olahraga',
    'career.job.4.desc': 'Pataka Consultant mencari Koordinator Event yang energik untuk mengelola event olahraga dan aktivasi komunitas.',
    'career.job.4.req.1': 'Pengalaman dalam perencanaan dan eksekusi event',
    'career.job.4.req.2': 'Keterampilan organisasi dan multitasking yang kuat',
    'career.job.4.req.3': 'Semangat untuk olahraga dan pengembangan komunitas',
    'career.job.4.req.4': 'Keterampilan interpersonal dan negosiasi yang sangat baik',
    'career.job.4.resp.1': 'Merencanakan dan mengeksekusi event olahraga dan program komunitas',
    'career.job.4.resp.2': 'Mengelola logistik event, vendor, dan anggaran',
    'career.job.4.resp.3': 'Berkoordinasi dengan pemasaran untuk promosi event',
    'career.job.4.resp.4': 'Memastikan kepuasan peserta yang tinggi dan keamanan event',

    'career.job.5.title': 'Konsultan (Strategi & Operasi)',
    'career.job.5.desc': 'Bergabunglah dengan PLN Consultant untuk membantu klien kami mengoptimalkan operasi bisnis mereka dan mencapai pertumbuhan strategis.',
    'career.job.5.req.1': 'Kerangka analitis dan pemecahan masalah yang kuat',
    'career.job.5.req.2': 'Pengalaman dalam konsultasi bisnis atau manajemen operasional',
    'career.job.5.req.3': 'Kemampuan untuk memimpin proyek dan mengelola banyak pemangku kepentingan',
    'career.job.5.req.4': 'Keterampilan presentasi dan komunikasi yang sangat baik',
    'career.job.5.resp.1': 'Mengembangkan strategi bisnis dan rencana peningkatan operasional',
    'career.job.5.resp.2': 'Mengelola garis waktu proyek dan hasil kerja',
    'career.job.5.resp.3': 'Melakukan riset pasar dan analisis kompetitif',
    'career.job.5.resp.4': 'Memfasilitasi lokakarya dan pertemuan klien',
  },
  en: {
    'brand.name': 'Ardana Perkasa Group',
    'brand.short': 'APG',
    'brand.logoAlt': 'APG Logo',

    // Navigation
    'nav.home': 'Home',
    'nav.about': 'Company Profile',
    'nav.structure': 'Organization Structure',
    'nav.subsidiaries': 'Subsidiaries',
    'nav.announcements': 'Announcements',
    'nav.news': 'News',
    'announcements.news.desc': 'Latest updates, corporate notices, and APG activities relevant to the public.',
    'nav.contact': 'Contact Us',
    'nav.menu.open': 'Open main menu',
    'nav.menu.close': 'Close main menu',
    'nav.menu.label': 'Menu',
    'nav.services': 'Services',
    'nav.information': 'Information',
    'nav.career': 'Career',
    'nav.annual_report': 'Annual Report',
    'nav.achievements': 'Achievements',
    'nav.testimonials': 'Testimonials',
    'nav.gallery': 'APG Gallery',
    'nav.vision_mission': 'Vision & Mission',
    'nav.language': 'Language',
    'nav.aria': 'Main navigation',
    'nav.about_history': 'About the Company',
    'nav.about_history.desc': 'A concise overview of APG’s journey and the foundation behind its holding ecosystem.',
    'nav.vision_mission.desc': 'APG’s strategic direction and long-term commitment to sustainable growth.',
    'nav.gallery.desc': 'Corporate activities and key APG moments presented visually.',
    'nav.structure_chart': 'Organization Chart',
    'nav.management': 'Management',
    'nav.subsidiaries_all': 'View All Subsidiaries',
    'org.chart.header': 'ORGANIZATION STRUCTURE OF PT ARDANA PERKASA GROUP',
    'org.chart.gm': 'GENERAL MEETING OF',
    'org.chart.gm.2': 'SHAREHOLDERS',
    'org.chart.board': 'BOARD OF COMMISSIONERS',
    'org.chart.ceo.1': 'PRESIDENT',
    'org.chart.ceo.2': 'DIRECTOR',
    'org.chart.opsdir.1': 'OPERATIONS',
    'org.chart.opsdir.2': 'DIRECTOR',
    'org.chart.head.finance': 'HEAD OF FINANCE',
    'org.chart.head.it': 'HEAD OF IT',
    'org.chart.head.support': 'HEAD OF SUPPORT',
    'org.chart.head.ops': 'HEAD OF OPERATIONS',
    'org.chart.spv.acc': 'SPV ACCOUNTING, TAX &\nREPORTING',
    'org.chart.staff.acc': 'ACCOUNTING STAFF',
    'org.chart.staff.tax': 'TAX STAFF',
    'org.chart.spv.finance': 'SPV FINANCE &\nCORPORATE PLANNING',
    'org.chart.staff.finance': 'FINANCE STAFF',
    'org.chart.staff.bizplan.1': 'BUSINESS PLAN',
    'org.chart.staff.bizplan.2': 'STAFF',
    'org.chart.spv.itprog': 'SPV IT PROGRAMMER',
    'org.chart.staff.itprog.1': 'IT PROGRAMMER\nSTAFF 1',
    'org.chart.staff.itprog.2': 'IT PROGRAMMER\nSTAFF 2',
    'org.chart.staff.itprog.3': 'IT PROGRAMMER\nSTAFF 3',
    'org.chart.staff.itprog.4': 'IT PROGRAMMER\nSTAFF 4',
    'org.chart.staff.itprog.5': 'IT PROGRAMMER\nSTAFF 5',
    'org.chart.staff.itprog.6': 'IT PROGRAMMER\nSTAFF 6',
    'org.chart.spv.itsupport': 'SPV IT SUPPORT',
    'org.chart.staff.itsupport.1': 'IT SUPPORT\nSTAFF 1',
    'org.chart.staff.itsupport.2': 'IT SUPPORT\nSTAFF 2',
    'org.chart.staff.itsupport.3': 'IT SUPPORT\nSTAFF 3',
    'org.chart.spv.marketing': 'SPV MARKETING',
    'org.chart.staff.digital': 'DIGITAL\nMARKETING STAFF',
    'org.chart.staff.markexec.1': 'MARKETING',
    'org.chart.staff.markexec.2': 'EXECUTIVE STAFF',
    'org.chart.spv.compliance': 'SPV COMPLIANCE',
    'org.chart.staff.audit.1': 'INTERNAL',
    'org.chart.staff.audit.2': 'AUDIT STAFF',
    'org.chart.staff.legal.1': 'LEGAL &',
    'org.chart.staff.legal.2': 'COMPLIANCE STAFF',
    'org.chart.spv.hr': 'SPV HR & GENERAL',
    'org.chart.staff.hr': 'HR STAFF',
    'org.chart.staff.general': 'GENERAL STAFF',
    'org.chart.spv.cosec.1': 'SPV CORPORATE',
    'org.chart.spv.cosec.2': 'SECRETARY',
    'org.chart.staff.relations.1': 'INSTITUTIONAL',
    'org.chart.staff.relations.2': 'RELATIONS STAFF',
    'org.chart.staff.corpcom.1': 'CORPORATE',
    'org.chart.staff.corpcom.2': 'COMMUNICATION',
    'org.chart.exec.driver.1': 'EXECUTING',
    'org.chart.exec.driver.2': 'DRIVER 1',
    'org.chart.exec.driver2.1': 'EXECUTING',
    'org.chart.exec.driver2.2': 'DRIVER 2',
    'org.chart.exec.ob.1': 'EXECUTING',
    'org.chart.exec.ob.2': 'OFFICE BOY',
    'org.chart.exec.courier.1': 'EXECUTING',
    'org.chart.exec.courier.2': 'COURIER',
    'language.id.aria': 'Indonesian',
    'language.en.aria': 'English',

    // Hero
    'hero.headline': 'Building Cross-Sector Ecosystem with Enterprise Standards',
    'hero.subheadline': 'APG is a holding company that develops cross-sector business ecosystems with enterprise governance.',
    'hero.illustrationAlt': 'APG hero illustration',
    'hero.cta.discover': 'Discover Subsidiaries',
    'hero.cta.ecosystem': 'Explore Ecosystem',
    'hero.about.badge': 'About APG Holding',
    'hero.about.p1':
      'APG is a holding company overseeing subsidiaries that support financial institutions, including PT. Buana Perkasa Rajanegara (BPR Bonding), PT. Dwi Kusuma Perkasa (DWP Insurance), PT. Perkasa Lintas Nasional Consultant (PLN Consultant), and PT. Pataka Prima Perkasa Consultant (Pataka Consultant).',
    'hero.about.p2':
      'APG also expands into the sports sector, widening its reach to support industries that contribute to economic and social development.',
    'hero.vision.title': 'Vision',
    'hero.vision.desc': 'To become a trusted and leading partner in supporting the financial institution ecosystem and the development of the sports industry.',
    'hero.mission.title': 'Mission',
    'hero.mission.desc': 'To deliver comprehensive, reliable, and innovative solutions that drive economic and social growth.',
    'hero.cta.learnMore': 'Learn more about our company',
    'hero.mock.tag': 'Workspace',
    'hero.mock.accounts.label': 'Accounts',
    'hero.mock.accounts.value': 'Stable growth',
    'hero.mock.reports.label': 'Reports',
    'hero.mock.reports.value': 'Secure data',
    'hero.mock.years.label': 'Years Experience',
    'hero.mock.years.value': 'Industry leadership',

    // Intro
    'intro.badge': 'Supporting Finance & Sports Ecosystems',
    'intro.title.part1': 'Driving Growth',
    'intro.title.highlight': 'Across Industries',
    'intro.title.part2': 'Through Strategic Innovation & Strong Partnerships.',
    'intro.desc': 'Ardana Perkasa Group (APG) is a holding company with subsidiaries supporting financial institutions and sports.',
    'intro.cta.primary': 'Explore Our Businesses',
    'intro.cta.secondary': 'View Annual Report',
    'intro.card.1.title': 'Global Reach',
    'intro.card.1.desc': 'Connecting partners and business networks across sectors.',
    'intro.card.2.title': 'Trusted Security',
    'intro.card.2.desc': 'Enterprise standards for reliable data and processes.',
    'intro.card.3.title': 'Sustainable Growth',
    'intro.card.3.desc': 'Consistent year-over-year ecosystem expansion.',
    'intro.card.4.title': 'Infrastructure',
    'intro.card.4.desc': 'Building an operational backbone for modern execution.',

    'trust.inline': 'Trusted by 200+ partners across industries',

    'hero.card.partners.label': 'Partners',
    'hero.card.partners.value': '200+',
    'hero.card.industries.label': 'Industries',
    'hero.card.industries.value': '10',

    // Overview
    'overview.tag': 'Company Overview',
    'overview.title': 'Enterprise Governance. Cross-Sector Execution.',
    'overview.desc': 'We build a structured holding ecosystem—connecting capital, capability, and partnerships to deliver sustainable growth.',
    'overview.value.1.title': 'Strategic Vision',
    'overview.value.1.desc': 'A multi-sector holding group focused on governance, synergy, and long-term value.',
    'overview.value.2.title': 'Governance Excellence',
    'overview.value.2.desc': 'Developing portfolios across finance, insurance, consulting, sports, and solutions with disciplined execution.',
    'overview.value.3.title': 'Sustainable Expansion',
    'overview.value.3.desc': 'To be a trusted strategic partner driving cross-industry growth through innovation and compliance.',
    'overview.value.4.title': 'Ecosystem Partnership',
    'overview.value.4.desc': 'Building long-term collaborations that strengthen ecosystems and portfolio resilience.',
    'overview.highlight.1.value': '25+',
    'overview.highlight.1.label': 'Years Experience',
    'overview.highlight.2.value': '15+',
    'overview.highlight.2.label': 'Subsidiaries',
    'overview.highlight.3.value': '200+',
    'overview.highlight.3.label': 'Partners',
    'overview.highlight.4.value': '10',
    'overview.highlight.4.label': 'Industries',
    'overview.cta.primary': 'Explore Our Businesses',
    'overview.cta.secondary': 'View Company Profile',

    // Career
    'career.nav': 'Career',
    'career.hero.tag': 'Careers at APG',
    'career.hero.title': 'Build Your Career Across Industries',
    'career.hero.subtitle': 'Join Ardana Perkasa Group and grow within a dynamic cross-sector ecosystem.',
    'career.hero.cta.open': 'View Openings',
    'career.hero.cta.companies': 'View Companies',

    'career.filter.company': 'Company',
    'career.filter.location': 'Location',
    'career.filter.category': 'Category',
    'career.filter.all': 'All',
    'career.job.apply': 'Apply Now',
    'career.job.detail': 'Job Detail',
    'career.why.title': 'Why Join Us',
    'career.why.subtitle': 'We offer more than just a job—we offer a growth path.',
    'career.life.title': 'Life at APG Holding',
    'career.life.subtitle': 'Our collaborative and innovative culture is the key to shared success.',
    'career.cta.title': 'Start Your Journey With Us',
    'career.cta.subtitle': 'Find the right opportunity for your future.',
    'career.cta.apply': 'Apply Now',
    'career.cta.contact': 'Contact HR',
    'career.empty': 'No job openings found.',
    'career.modal.responsibilities': 'Responsibilities',
    'career.modal.requirements': 'Requirements',
    'career.modal.close': 'Close',
    'career.intro.headline': 'Build Your Career with Ardana Perkasa Group',
    'career.intro.subtext': 'We are always looking for top talent to grow with our business ecosystem. Find career opportunities that match your interests and expertise.',
    'career.why_join.title': 'Why Build Your Career at APG?',
    'career.why_join.1.title': 'Professional & Growing',
    'career.why_join.1.desc': 'A dynamic work environment that supports your competence growth.',
    'career.why_join.2.title': 'Cross-Industry',
    'career.why_join.2.desc': 'Opportunities to explore careers in various holding business sectors.',
    'career.why_join.3.title': 'Holding Stability',
    'career.why_join.3.desc': 'Career security within a solid and sustainable business ecosystem.',
    'career.why_join.4.title': 'Innovation & Collaboration',
    'career.why_join.4.desc': 'Modern work culture that values creative ideas and teamwork.',
    'struktur.sectors.title': 'Explore Opportunities Across Sectors',
    'struktur.komisaris': 'Board of Commissioners',
    'struktur.direktur_utama': 'President Director',
    'struktur.direktur': 'Director',
    'struktur.manager_keuangan': 'Finance Manager',
    'struktur.manager_operasional': 'Operations Manager',
    'struktur.supervisor_keuangan': 'Finance Supervisor',
    'struktur.kadiv_keuangan': 'Head of Finance',
    'struktur.kadiv_operasional': 'Head of Operations',
    'struktur.supervisor_it': 'IT Supervisor',
    'struktur.staff_keuangan': 'Finance Staff',
    'struktur.staff_operasional': 'Operations Staff',
    'struktur.management': 'Management',
    'career.search.guidance.title': 'Start Your Career Search',
    'career.search.guidance.desc': 'Search for position, field, or company name to find suitable opportunities.',
    'career.search.suggested': 'Popular Searches:',
    'career.search.results_for': 'Search results for:',
    'career.keywords.it': 'IT',
    'career.keywords.finance': 'Finance',
    'career.keywords.marketing': 'Marketing',
    'career.keywords.hr': 'HR',
    'career.keywords.operasional': 'Operations',
    'career.jobs_found_single': 'job opening found',
    'career.jobs_found_plural': 'job openings found',
    'career.job.type.full_time': 'Full-time',
    'career.job.type.contract': 'Contract',
    'career.job.type.internship': 'Internship',
    'career.job.cta.detail': 'Job Detail',
    'career.job.cta.apply': 'Apply Now',
    'career.search.placeholder': 'Search for position or company...',
    'career.search.button': 'Search',
    'career.reset_filter': 'Reset Filter',
    'career.job_not_found': 'Pekerjaan Tidak Ditemukan',
    'career.empty.message': 'Maaf, kami tidak menemukan lowongan yang sesuai dengan kata kunci',
    'career.search.try_other': 'Coba gunakan kata kunci lain atau reset filter.',
    'career.all_jobs': 'Semua Pekerjaan',
    'career.category.tech': 'Teknologi',
    'career.category.finance': 'Keuangan',
    'career.category.marketing': 'Pemasaran',
    'career.category.hr': 'SDM',
    'career.category.operations': 'Operasional',

    // Metrics
    'metrics.subsidiaries': 'Subsidiaries',
    'metrics.partners': 'Partners',
    'metrics.sectors': 'Sectors',
    'metrics.tag': 'STATISTICS',
    'metrics.title': 'Measured Scale. Proven Execution.',
    'metrics.desc': 'Key indicators that reflect APG’s growth, reach, and ecosystem strength.',
    'metrics.caption': 'Enterprise-scale indicators',

    // About Preview
    'about.preview.tag': 'About Us',
    'about.preview.title': 'Ardana Perkasa Group at a Glance',
    'about.preview.desc': 'Ardana Perkasa Group (APG) is a strategic holding entity focused on developing a sustainable business ecosystem.',
    'about.preview.cta': 'Learn More About Us',
    'about.preview.imageAlt': 'Ardana Perkasa Group - Enterprise Holding',

    // Business Focus
    'focus.tag': 'BUSINESS ECOSYSTEM',
    'focus.title.part1': 'Cross-Sector Synergy for a',
    'focus.title.part2': 'Future',
    'focus.1.title': 'Governance',
    'focus.1.desc': 'A GCG framework for transparent, measurable decision-making.',
    'focus.2.title': 'Compliance',
    'focus.2.desc': 'Regulation-aligned processes that reduce risk and sustain trust.',
    'focus.3.title': 'Innovation',
    'focus.3.desc': 'Modern solutions that accelerate growth and improve competitiveness.',
    'focus.4.title': 'Partnerships',
    'focus.4.desc': 'Long-term collaboration that expands cross-industry impact.',
    'focus.5.title': 'Execution',
    'focus.5.desc': 'Disciplined implementation with enterprise standards across the portfolio.',

    // Ecosystem
    'ecosystem.tag': 'Business Ecosystem',
    'ecosystem.title.part1': 'An Integrated Portfolio for ',
    'ecosystem.title.part2': 'Sustainable Growth',
    'ecosystem.finance': 'Finance',
    'ecosystem.insurance': 'Insurance',
    'ecosystem.consulting': 'Consulting',
    'ecosystem.sports': 'Sports',
    'ecosystem.solutions': 'Solutions',
    'ecosystem.finance.tag': 'Integrated financial services.',
    'ecosystem.insurance.tag': 'Asset & risk protection.',
    'ecosystem.consulting.tag': 'Adaptive business strategy.',
    'ecosystem.sports.tag': 'Dynamic sports ecosystem.',
    'ecosystem.solutions.tag': 'Smart operational solutions.',

    // Subsidiaries
    'subsidiaries.tag': 'INSTITUTIONAL NETWORK',
    'subsidiaries.title': 'Enterprise Ecosystem',
    'subsidiaries.desc': 'Building cross-sector synergy through selected subsidiaries that are leaders in their fields.',
    'subsidiaries.cta': 'Explore All Subsidiaries',
    'subsidiaries.card.cta': 'View Details',
    'subsidiaries.card.label': 'Subsidiary',

    // Why Choose Us
    'why.tag': 'Strategic Value Pillars',
    'why.title': 'Our Institutional Framework',
    'why.desc': 'We operate with enterprise governance standards, ensuring every strategic initiative delivers sustainable value and strengthens holding ecosystem resilience.',
    'why.1.title': 'Strategic Vision',
    'why.1.desc': 'Long-term focus on cross-sector synergy, steering portfolios toward market leadership.',
    'why.2.title': 'Governance Excellence',
    'why.2.desc': 'Highest compliance standards and risk management to maintain stakeholder trust.',
    'why.3.title': 'Sustainable Growth',
    'why.3.desc': 'Measured expansion centered on value creation, economic resilience, and environmental responsibility.',
    'why.4.title': 'Ecosystem Partnership',
    'why.4.desc': 'Strategic alliances that strengthen supply chains and expand national execution capacity.',

    // Leadership
    'leadership.tag': 'LEADERSHIP',
    'leadership.title': 'Led by Experienced Professionals',
    'leadership.desc': 'A management team focused on governance, strategy, and outcome-driven execution.',
    'leadership.1.role': 'President Commissioner',
    'leadership.2.role': 'Commissioner',
    'leadership.3.role': 'President Director',
    'leadership.4.role': 'Operations Director',
    'leadership.5.role': 'Finance Director',

    // News/Insights
    'news.1.tag': 'Strategy',
    'news.1.title': 'APG Holding Initiates Strategic Expansion in Sports Technology',
    'news.1.excerpt': 'Exploring new synergies between financial services and sports infrastructure to drive ecosystem growth in 2025.',
    'news.2.tag': 'Governance',
    'news.2.title': 'Quarterly Governance Report: Strengthening Enterprise Transparency',
    'news.2.excerpt': 'A comprehensive look at our updated GCG framework and its impact on subsidiary operational excellence.',
    'news.3.tag': 'Innovation',
    'news.3.title': 'Digital Ecosystem Integration: Standardizing Cross-Sector Infrastructure',
    'news.3.excerpt': 'Implementing unified digital platforms to enhance collaboration and data security across all APG holdings.',
    'news.3.date': 'April 15, 2025',

    // Gallery
    'gallery.item.1.title': 'Strategic Leadership Summit',
    'gallery.item.1.category': 'Corporate',
    'gallery.item.2.title': 'Office Operational Synergy',
    'gallery.item.2.category': 'Operations',
    'gallery.item.3.title': 'Digital Ecosystem Innovation',
    'gallery.item.3.category': 'Technology',
    'gallery.item.4.title': 'Athlete Development Facility',
    'gallery.item.4.category': 'Sports',
    'gallery.item.5.title': 'Corporate Governance Audit',
    'gallery.item.5.category': 'Governance',
    'gallery.item.6.title': 'Annual Ecosystem Awards',
    'gallery.item.6.category': 'Achievement',
    'gallery.tag.enterprise_activities': 'Enterprise Activities',

    // Insights
    'insights.tag': 'INSIGHTS',
    'insights.title': 'News & Insights',
    'insights.desc': 'Perspectives, updates, and ecosystem stories to keep the site active and relevant.',
    'insights.cta': 'View All',
    'insights.readMore': 'Read More',
    'insights.tag.corporate_insights': 'Corporate Insights',
    'insights.1.tag': 'Corporate',
    'insights.1.title': 'Strengthening Competitiveness through Portfolio Synergy',
    'insights.1.excerpt': 'How a holding strategy aligns cross-sector capabilities to deliver sustainable growth.',
    'insights.1.date': 'May 12, 2025',
    'insights.2.tag': 'Governance',
    'insights.2.title': 'Governance as a Competitive Advantage',
    'insights.2.excerpt': 'Why enterprise standards and compliance strengthen trust with partners and stakeholders.',
    'insights.2.date': 'April 28, 2025',
    'insights.3.tag': 'Ecosystem',
    'insights.3.title': 'Building a Modern & Adaptive Business Ecosystem',
    'insights.3.excerpt': 'APG’s approach to developing a resilient ecosystem amid changing markets.',
    'insights.3.date': 'April 15, 2025',

    // Ecosystem Extra
    'ecosystem.strategic_ecosystem': 'Strategic Ecosystem',
    'ecosystem.strategic_desc': 'A diversified portfolio connected by enterprise governance and shared strategic vision.',
    'ecosystem.explore_title': 'Explore Full Ecosystem',
    'ecosystem.explore_desc': 'Discover how our subsidiaries synergize to create national impact.',
    'ecosystem.explore_cta': 'View Portfolio',

    // CTA
    'cta.tag': 'COLLABORATION',
    'cta.title': 'Let’s Build the Future Together',
    'cta.desc': 'Start a conversation for collaboration, partnerships, or cross-sector strategic opportunities.',
    'cta.primary': 'Contact Us',
    'cta.secondary': 'Partner With Us',

    // Trust
    'trust.partners': 'Trusted by Leading Partners',
    'trust.partnerAlt': 'Partner',
    'trust.cta.title': 'Let\'s Build Synergy Together',
    'trust.cta.button': 'Contact Us',
    'trust.testimonial.1.quote': 'APG is a strategic partner that elevates enterprise execution standards to the next level.',
    'trust.testimonial.1.author': 'Strategic Partner',
    'trust.testimonial.2.quote': 'Strong governance and cross-sector synergy make APG a visionary holding group.',
    'trust.testimonial.2.author': 'Subsidiary Director',

    // Process
    'process.tag': 'WORK PROCESS',
    'process.title': 'Standard Work Process',
    'process.desc': 'A standardized workflow to ensure execution quality, transparency, and measurable outcomes.',
    'process.step1.title': 'Discovery',
    'process.step1.desc': 'Clarify goals, constraints, and the business context.',
    'process.step2.title': 'Planning',
    'process.step2.desc': 'Define scope, timeline, and success metrics (KPIs).',
    'process.step3.title': 'Execution',
    'process.step3.desc': 'Deliver with continuous monitoring and quality control.',
    'process.step4.title': 'Reporting',
    'process.step4.desc': 'Report progress and iterate for continuous improvement.',

    // Gallery
    'gallery.tag': 'CORPORATE ACTIVITIES',
    'gallery.title': 'Life at APG Holding',
    'gallery.cta': 'View Full Gallery',
    'gallery.images.meeting': 'Corporate Meeting',
    'gallery.images.collaboration': 'Office Collaboration',
    'gallery.images.success': 'Team Success',

    // Illustration
    'illustration.tag': 'INTERACTIVE ILLUSTRATION',
    'illustration.title': 'Make the homepage feel alive with smooth UI animations.',
    'illustration.desc': 'Small elements around the illustration move subtly to feel modern without distracting the user.',
    'illustration.badge.ui': 'UI',
    'illustration.badge.done': 'Done',
    'illustration.badge.checklist': 'Checklist',

    // Scroll Cinema
    'cinema.brand': 'Ardana Perkasa Group',
    'cinema.title': 'Driving Sustainable Growth Through Innovation',
    'cinema.desc': 'We deliver integrated solutions to drive sustainable business growth.',

    // Not Found
    'notFound.tag': 'NOT FOUND',
    'notFound.desc': 'The page you are looking for could not be found.',
    'notFound.cta': 'Back to Home',

    // Testimonials
    'testimoni.tag': 'TESTIMONIALS',
    'testimoni.title': 'What People Say About Us',
    'testimoni.desc': 'We’re proud of the relationships we’ve built with our partners and subsidiaries. Here are some testimonials from them.',
    'testimoni.placeholder.quote': '“This section will showcase full testimonials from our partners and subsidiaries.”',
    'testimoni.placeholder.author': '— Ardana Perkasa Group Team',

    // Subsidiary Detail
    'subsidiary.detail.tag': 'SUBSIDIARY PROFILE',
    'subsidiary.detail.back': 'Back to Subsidiaries',
    'subsidiary.detail.highlights': 'Highlights',
    'subsidiary.detail.alignment.title': 'Alignment',
    'subsidiary.detail.alignment.desc': 'All subsidiaries operate within APG’s governance and portfolio management framework to ensure consistent standards, risk management, and KPI-driven execution.',
    'subsidiary.detail.alignment.1': 'Governance-first operating model',
    'subsidiary.detail.alignment.2': 'Transparent reporting and controls',
    'subsidiary.detail.alignment.3': 'Cross-sector synergy and capabilities',
    'subsidiary.detail.alignment.4': 'Disciplined execution for growth',
    'subsidiary.detail.value_creation': 'Value Creation',
    'subsidiary.detail.strategic_matrix': 'Strategic Matrix',

    'subsidiary.bpr.sector': 'Insurance & Guarantee Agent',
    'subsidiary.bpr.desc': 'Bank Guarantee and Surety Bond services delivered with disciplined governance standards.',
    'subsidiary.bpr.highlight.1': 'Service proximity',
    'subsidiary.bpr.highlight.2': 'Risk discipline',
    'subsidiary.bpr.highlight.3': 'Portfolio alignment',

    'subsidiary.dwp.sector': 'Insurance & Guarantee Agent',
    'subsidiary.dwp.desc': 'Guarantee and risk protection solutions to support institutional needs and portfolio execution.',
    'subsidiary.dwp.highlight.1': 'Event activation',
    'subsidiary.dwp.highlight.2': 'Brand partnerships',
    'subsidiary.dwp.highlight.3': 'Community engagement',

    'subsidiary.sipbro.sector': 'Insurance & Guarantee Agent',
    'subsidiary.sipbro.desc': 'An integrated guarantee information system to improve efficiency, accuracy, and service monitoring.',
    'subsidiary.sipbro.highlight.1': 'Operational tooling',
    'subsidiary.sipbro.highlight.2': 'Service enablement',
    'subsidiary.sipbro.highlight.3': 'Performance discipline',

    'subsidiary.pln.sector': 'Sport Equipment Supplier',
    'subsidiary.pln.desc': 'Consulting and operational advisory to strengthen portfolio execution and governance.',
    'subsidiary.pln.highlight.1': 'Cross-function enablement',
    'subsidiary.pln.highlight.2': 'Standardized delivery',
    'subsidiary.pln.highlight.3': 'Enterprise execution',

    'subsidiary.qjamin.sector': 'Digital Guarantee',
    'subsidiary.qjamin.desc': 'Assurance and governance support to maintain portfolio execution quality.',
    'subsidiary.qjamin.highlight.1': 'Assurance & controls',
    'subsidiary.qjamin.highlight.2': 'Governance alignment',
    'subsidiary.qjamin.highlight.3': 'Quality monitoring',

    'subsidiary.proteksi.sector': 'Insurance',
    'subsidiary.proteksi.desc': 'Protection services that strengthen the ecosystem’s financial and operational resilience.',
    'subsidiary.proteksi.highlight.1': 'Protection framework',
    'subsidiary.proteksi.highlight.2': 'Customer-first service',
    'subsidiary.proteksi.highlight.3': 'Compliance-ready operations',

    'subsidiary.pataka.sector': 'Sports',
    'subsidiary.pataka.desc': 'Community development initiatives for a sustainable sports ecosystem.',
    'subsidiary.pataka.highlight.1': 'Community activation',
    'subsidiary.pataka.highlight.2': 'Partnership model',
    'subsidiary.pataka.highlight.3': 'Brand & ecosystem growth',

    'subsidiary.prada-bc.sector': 'Sports Club',
    'subsidiary.prada-bc.desc': 'Athlete development and sports ecosystem growth with professional facilities and standards.',
    'subsidiary.prada-bc.highlight.1': 'Portfolio execution support',
    'subsidiary.prada-bc.highlight.2': 'KPI-based delivery',
    'subsidiary.prada-bc.highlight.3': 'Enterprise governance alignment',

    'subsidiary.lps.sector': 'Insurance & Guarantee Agent',
    'subsidiary.lps.desc': 'Governance capabilities and control standardization to ensure operational consistency.',
    'subsidiary.lps.highlight.1': 'Policy & controls',
    'subsidiary.lps.highlight.2': 'Reporting discipline',
    'subsidiary.lps.highlight.3': 'Risk visibility',

    'subsidiary.caraka-mulia.sector': 'Insurance Brokers & Consultants',
    'subsidiary.caraka-mulia.desc': 'Protection and risk management solutions for ecosystem resilience.',
    'subsidiary.caraka-mulia.highlight.1': 'Risk protection frameworks',
    'subsidiary.caraka-mulia.highlight.2': 'Compliance-ready operations',
    'subsidiary.caraka-mulia.highlight.3': 'Stakeholder assurance',

    // Tentang Page
    'tentang.hero.badge': 'Who We Are',
    'tentang.hero.title': 'Ardana Perkasa Group',
    'tentang.hero.p1': 'Ardana Perkasa Group (APG) is one of the leading holding companies in Indonesia, committed to driving stability and economic growth through innovative, reliable, and beneficial business solutions for shareholders and stakeholders.',
    'tentang.hero.p2': 'In addition to focusing on sectors supporting financial institutions, APG also expands its business reach into the sports sector, contributing to the development of the sports industry in Indonesia and creating added value for society and the economy.',

    'tentang.visi.badge': 'About Us',
    'tentang.visi.title': 'APG Vision',
    'tentang.visi.desc': 'To become one of the largest holding companies in Indonesia that supports stability and economic growth through innovative, reliable business services beneficial to shareholders and stakeholders.',

    'tentang.misi.badge': 'About Us',
    'tentang.misi.title': 'APG Mission',
    'tentang.misi.1.title': 'Building Competitive Advantage',
    'tentang.misi.1.desc': 'Developing a portfolio focused on solutions with the latest technology and superior services to meet the needs of shareholders and stakeholders.',
    'tentang.misi.2.title': 'Supporting Financial Stability',
    'tentang.misi.2.desc': 'Contributing to a stable economic ecosystem by providing credible, transparent guarantee products in accordance with regulations.',
    'tentang.misi.3.title': 'Increasing Customer Trust',
    'tentang.misi.3.desc': 'Creating added value for customers by providing accurate, fast, and solution-oriented services.',
    'tentang.misi.4.title': 'Supporting Subsidiary Business Growth',
    'tentang.misi.4.desc': 'Providing strategic, financial, and management support to subsidiaries to achieve sustainable growth.',
    'tentang.misi.5.title': 'Prioritizing Ethics and Compliance',
    'tentang.misi.5.desc': 'Running businesses with Good Corporate Governance (GCG) principles and complying with applicable regulations.',

    'tentang.gallery.badge': 'About Us',
    'tentang.gallery.title': 'Gallery',

    'tentang.contact.title': 'For further information please contact us at:',
    'tentang.contact.address.label': 'Address',
    'tentang.contact.address.value': 'The Mansion Bougenville, Office Tower Fontana, Unit BF 32 B1 & B2, Jl. Trembesi Blok D Pademangan Timur, Kec. Pademangan, North Jakarta',
    'tentang.contact.email.label': 'Email',
    'tentang.contact.email.value': 'info@ardanaperkasagroup.id',
    'tentang.contact.phone.label': 'Telephone',
    'tentang.contact.phone.value': '021 3893 0088',

    // Struktur Page
    'struktur.title': 'Organization Structure',
    'struktur.tag': 'Leadership',
    'struktur.desc': 'Led by experienced professionals to orchestrate cross-sector synergy.',
    'struktur.direksi': 'Board of Directors',
    'struktur.divisi': 'Division Heads',
    'struktur.cta.title': 'Want to Join Our Ecosystem?',
    'struktur.cta.desc': 'We are always open to strategic collaboration and professional talent.',
    'struktur.cta.view': 'VIEW FULL PROFILE',

    // Common
    'common.contact_us': 'Contact Us',
    'common.learn_more': 'Learn More',
    'footer.tagline': 'Enterprise holding company focused on governance, synergy, and portfolio growth.',
    'footer.cta.title': 'Connect with Us',
    'footer.cta.desc': 'Build strategic collaboration and access official information from Ardana Perkasa Group through our communication channels.',
    'footer.location.label': 'Location',
    'footer.location.value': 'North Jakarta',
    'footer.phone.label': 'Phone',
    'footer.phone.value': '0812 8888 5132',
    'footer.email.label': 'Email',
    'footer.email.value': 'info@apg.co.id',
    'footer.hours.label': 'Business Hours',
    'footer.hours.value': 'Mon–Fri, 09:00–17:00 WIB',
    'footer.nav.title': 'Navigation',
    'footer.social.title': 'Social Media',
    'footer.social.linkedin': 'LinkedIn',
    'footer.social.instagram': 'Instagram',
    'footer.social.x': 'X',
    'footer.social.facebook': 'Facebook',
    'footer.social.youtube': 'YouTube',
    'footer.social.tiktok': 'TikTok',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms',
    'footer.legal.security': 'Security',
    'footer.copyright': '© {year} {brand}. All rights reserved.',

    // Contact Page
    'contact.tag': 'CONTACT',
    'contact.title': 'Contact Us',
    'contact.desc': 'For collaboration, partnerships, or corporate solutions, the APG team is ready to connect.',
    'contact.map.title': 'Map location of Ardana Perkasa Group - North Jakarta',
    'contact.card.address.title': 'Address',
    'contact.card.address.value': 'The Mansion Bougenville, Office Tower Fontana, North Jakarta',
    'contact.card.email.title': 'Email',
    'contact.card.email.value': 'info@apg.co.id',
    'contact.card.phone.title': 'Phone',
    'contact.card.phone.value': '0812 8888 5132',
    'contact.card.hours.title': 'Business Hours',
    'contact.card.hours.value': 'Mon–Fri, 09:00–17:00 WIB',
    'contact.form.title': 'Send a Message',
    'contact.form.desc': 'Leave a message and our team will get back to you shortly.',
    'contact.form.name': 'Name',
    'contact.form.name.placeholder': 'Full name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'Email address',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Write your message...',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Your message has been sent successfully. Our team will contact you soon.',
    'contact.form.error': 'An error occurred while sending the message. Please try again.',
    'contact.form.direct': 'Direct Inquiry',
    'contact.form.sent': 'Sent',

    // AI Assistant
    'ai.button': 'Ask AI',
    'ai.send': 'Send',
    'ai.name': 'Ardana Assistant',
    'ai.subtitle': 'Ask anything • Friendly answers',
    'ai.aria.close': 'Close assistant',
    'ai.aria.open': 'Open assistant',
    'ai.typing': 'Typing…',
    'ai.placeholder': 'Type a message…',
    'ai.error': 'Sorry — I couldn’t respond right now. Please try again.',
    'ai.greeting': 'Hi! I’m here to help. What would you like to ask?',
    'ai.suggestion.1': 'Summarize APG in 3 sentences',
    'ai.suggestion.2': 'Give me a tagline idea',
    'ai.suggestion.3': 'Help write a professional email',

    // Footer Additional
    'footer.col.corporate': 'Corporate',
    'footer.col.governance': 'Governance',
    'footer.col.connect': 'Connect',
    'footer.gov.directors': 'Board of Directors',
    'footer.gov.guidelines': 'Corporate Guidelines',
    'footer.gov.sustainability': 'Sustainability Report',
    'footer.gov.investor': 'Investor Relations',
    'footer.gov.conduct': 'Code of Conduct',
    'footer.holding_company': 'Holding Company',

    // Tentang Extra
    'tentang.corporate_narrative': 'Corporate Narrative',
    'tentang.access_gateway': 'Corporate Access Gateway',
    'tentang.info_center': 'APG Information Center',
    'tentang.info_desc': 'Our team is ready to serve various strategic needs, investments, and inquiries regarding the holding portfolio.',
    'tentang.sub.visi_misi.title': 'Vision & Mission',
    'tentang.sub.visi_misi.desc': 'APG’s strategic direction and commitment to deliver sustainable growth through enterprise-grade governance.',
    'tentang.sub.gallery.title': 'APG Gallery',
    'tentang.sub.gallery.desc': 'A curated look at corporate moments, team activities, and APG’s business ecosystem in one place.',

    // Struktur Extra
    'struktur.governance_inquiry': 'Governance Inquiry',
    'struktur.finance_head': 'Finance Head',
    'struktur.ops_head': 'Operations Head',
    'struktur.it_supervisor': 'IT Supervisor',
    'visual.governance': 'Governance',
    'visual.board_directors': 'Board of Directors',
    'visual.ecosystem': 'Ecosystem',
    'visual.high_growth': 'High Growth',
    'visual.companies': 'Companies',
    'visual.sectors': 'Sectors',
    'visual.headquarters': 'Headquarters',
    'visual.jakarta_indonesia': 'Jakarta, Indonesia',

    // Career Jobs Data

    // Career Jobs Data
    'career.job.1.title': 'Software Engineer (Frontend)',
    'career.job.1.desc': 'We are looking for a Software Engineer to join our growing tech team and build modern web applications for our digital ecosystem.',
    'career.job.1.req.1': '3+ years of experience with React/Next.js',
    'career.job.1.req.2': 'Proficiency in TypeScript and modern CSS (Tailwind)',
    'career.job.1.req.3': 'Experience with state management and API integration',
    'career.job.1.req.4': 'Strong problem-solving skills and attention to detail',
    'career.job.1.resp.1': 'Develop and maintain high-quality web applications',
    'career.job.1.resp.2': 'Collaborate with designers and backend engineers',
    'career.job.1.resp.3': 'Optimize applications for performance and scalability',
    'career.job.1.resp.4': 'Participate in code reviews and technical discussions',

    'career.job.2.title': 'Finance Analyst',
    'career.job.2.desc': 'BPR Bonding is seeking a Finance Analyst to support our financial reporting and strategic planning processes.',
    'career.job.2.req.1': 'Bachelor degree in Accounting or Finance',
    'career.job.2.req.2': 'Minimum 2 years of experience in financial analysis',
    'career.job.2.req.3': 'Proficiency in financial modeling and reporting tools',
    'career.job.2.req.4': 'Excellent analytical and communication skills',
    'career.job.2.resp.1': 'Prepare monthly and quarterly financial reports',
    'career.job.2.resp.2': 'Analyze financial performance and trends',
    'career.job.2.resp.3': 'Support the budgeting and forecasting process',
    'career.job.2.resp.4': 'Assist in internal and external audits',

    'career.job.3.title': 'Insurance Specialist',
    'career.job.3.desc': 'Join DWP Insurance as an Insurance Specialist to manage client claims and provide expert advice on risk management.',
    'career.job.3.req.1': 'Strong knowledge of insurance products and regulations',
    'career.job.3.req.2': 'Minimum 3 years of experience in the insurance industry',
    'career.job.3.req.3': 'Ability to build and maintain client relationships',
    'career.job.3.req.4': 'Professional certification in insurance (AAIK/AIIS) is a plus',
    'career.job.3.resp.1': 'Process insurance claims accurately and efficiently',
    'career.job.3.resp.2': 'Perform risk assessments for potential clients',
    'career.job.3.resp.3': 'Advise clients on coverage options and risk mitigation',
    'career.job.3.resp.4': 'Monitor market trends and competitor activities',

    'career.job.4.title': 'Sports Event Coordinator',
    'career.job.4.desc': 'Pataka Consultant is looking for an energetic Event Coordinator to manage sports events and community activations.',
    'career.job.4.req.1': 'Experience in event planning and execution',
    'career.job.4.req.2': 'Strong organizational and multitasking skills',
    'career.job.4.req.3': 'Passion for sports and community development',
    'career.job.4.req.4': 'Excellent interpersonal and negotiation skills',
    'career.job.4.resp.1': 'Plan and execute sports events and community programs',
    'career.job.4.resp.2': 'Manage event logistics, vendors, and budgets',
    'career.job.4.resp.3': 'Coordinate with marketing for event promotion',
    'career.job.4.resp.4': 'Ensure high participant satisfaction and event safety',

    'career.job.5.title': 'Consultant (Strategy & Operations)',
    'career.job.5.desc': 'Join PLN Consultant to help our clients optimize their business operations and achieve strategic growth.',
    'career.job.5.req.1': 'Strong analytical and problem-solving framework',
    'career.job.5.req.2': 'Experience in business consulting or operational management',
    'career.job.5.req.3': 'Ability to lead projects and manage multiple stakeholders',
    'career.job.5.req.4': 'Excellent presentation and communication skills',
    'career.job.5.resp.1': 'Develop business strategies and operational improvement plans',
    'career.job.5.resp.2': 'Manage project timelines and deliverables',
    'career.job.5.resp.3': 'Conduct market research and competitive analysis',
    'career.job.5.resp.4': 'Facilitate workshops and client meetings',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('id');

  useEffect(() => {
    const savedLang = localStorage.getItem('app-language') as Language | null;
    if (savedLang === 'id' || savedLang === 'en') {
      const id = window.setTimeout(() => setLanguageState(savedLang), 0);
      return () => window.clearTimeout(id);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('app-language', lang);
    } catch {
      // ignore storage errors
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
